import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./assets/globals.css";
import "./assets/css/bootstrap.rtl.min.css"
import "./assets/css/style.css"
import "./assets/css/responsive.css"
import Script from "next/script";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <div className="page-wrapper">

            <div id="preloader" className="preloader">
                <div className="animation-preloader">
                    <div className="spinner"></div>
                    <div className="txt-loading">
                        <span data-text-preloader="F" className="letters-loading"> F </span>
                        <span data-text-preloader="I" className="letters-loading"> I </span>
                        <span data-text-preloader="N" className="letters-loading"> N </span>
                        <span data-text-preloader="C" className="letters-loading"> C </span>
                        <span data-text-preloader="L" className="letters-loading"> L </span>
                        <span data-text-preloader="I" className="letters-loading"> I </span>
                        <span data-text-preloader="X" className="letters-loading"> X </span>
                    </div>
                    <p className="text-center">Loading</p>
                </div>
                <div className="loader">
                    <div className="row">
                        <div className="col-3 loader-section section-left">
                            <div className="bg"></div>
                        </div>
                        <div className="col-3 loader-section section-left">
                            <div className="bg"></div>
                        </div>
                        <div className="col-3 loader-section section-right">
                            <div className="bg"></div>
                        </div>
                        <div className="col-3 loader-section section-right">
                            <div className="bg"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="scroll-to-top scroll-to-target" data-target="html"><span className="fa fa-angle-up"></span>
            </div>


            <header className="main-header header-style-one header-1">

                <div className="header-lower">

                    <div className="main-box">

                        <div className="nav-outer">
                            <div className="logo-box">
                                <div className="logo">
                                    <a href="index.html"><img src="/images/black-logo.png" alt="" title="finclix"/></a>
                                </div>
                            </div>

                            <div className="outer-box">
                                <nav className="nav main-menu">
                                    <ul className="navigation">
                                        <li className="current dropdown">
                                            <a href="#">Home</a>
                                            <ul>
                                                <li><a href="index.html">Home page 01</a></li>
                                                <li><a href="index-2.html">Home page 02</a></li>
                                                <li><a href="index-3.html">Home page 03</a></li>
                                                <li><a href="index-4.html">Home page 04</a></li>
                                                <li><a href="index-5.html">Home page 05</a></li>
                                                <li><a href="index-6.html">Home page 06</a></li>
                                                <li><a href="index-7.html">Home page 07</a></li>
                                                <li className="dropdown">
                                                    <a href="#">Single Styles</a>
                                                    <ul>
                                                        <li><a href="index-1-single.html">Single Styles One</a></li>
                                                        <li><a href="index-2-single.html">Single Styles Two</a></li>
                                                        <li><a href="index-3-single.html">Single Styles Three</a></li>
                                                        <li><a href="index-4-single.html">Single Styles Four</a></li>
                                                        <li><a href="index-5-single.html">Single Styles Five</a></li>
                                                        <li><a href="index-6-single.html">Single Styles Six</a></li>
                                                        <li><a href="index-7-single.html">Single Styles Seven</a></li>
                                                    </ul>
                                                </li>
                                                <li className="dropdown">
                                                    <a href="#">Dark Styles</a>
                                                    <ul>
                                                        <li><a href="index-1-dark.html">Dark Styles One</a></li>
                                                        <li><a href="index-2-dark.html">Dark Styles Two</a></li>
                                                        <li><a href="index-3-dark.html">Dark Styles Three</a></li>
                                                        <li><a href="index-4-dark.html">Dark Styles Four</a></li>
                                                        <li><a href="index-5-dark.html">Dark Styles Five</a></li>
                                                        <li><a href="index-6-dark.html">Dark Styles Six</a></li>
                                                        <li><a href="index-7-dark.html">Dark Styles Seven</a></li>
                                                    </ul>
                                                </li>
                                                <li><a href="index-1-rtl.html">RTL Style</a></li>
                                            </ul>
                                        </li>
                                        <li className="dropdown">
                                            <a href="#">Pages</a>
                                            <ul>
                                                <li><a href="page-about.html">About</a></li>
                                                <li className="dropdown">
                                                    <a href="#">Projects</a>
                                                    <ul>
                                                        <li><a href="page-projects.html">Our Projects</a></li>
                                                        <li><a href="page-project-details.html">Project Details</a></li>
                                                    </ul>
                                                </li>
                                                <li className="dropdown">
                                                    <a href="#">Team</a>
                                                    <ul>
                                                        <li><a href="page-team.html">Our Team</a></li>
                                                        <li><a href="page-team-details.html">Team Details</a></li>
                                                    </ul>
                                                </li>
                                                <li><a href="page-testimonial.html">Testimonial</a></li>
                                                <li><a href="page-pricing.html">Pricing</a></li>
                                                <li><a href="page-faq.html">FAQ</a></li>
                                                <li><a href="page-404.html">Page 404</a></li>
                                            </ul>
                                        </li>
                                        <li className="dropdown">
                                            <a href="#">Services</a>
                                            <ul>
                                                <li><a href="page-services.html">Our Services</a></li>
                                                <li><a href="page-service-details.html">Service Details</a></li>
                                            </ul>
                                        </li>
                                        <li className="dropdown">
                                            <a href="#">Shop</a>
                                            <ul>
                                                <li><a href="shop-products.html">Products</a></li>
                                                <li><a href="shop-products-sidebar.html">Products with Sidebar</a></li>
                                                <li><a href="shop-product-details.html">Product Details</a></li>
                                                <li><a href="shop-cart.html">Cart</a></li>
                                                <li><a href="shop-checkout.html">Checkout</a></li>
                                            </ul>
                                        </li>
                                        <li className="dropdown">
                                            <a href="#">News</a>
                                            <ul>
                                                <li><a href="news-grid.html">News Grid</a></li>
                                                <li><a href="news-details.html">News Details</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="page-contact.html">Contact</a></li>
                                    </ul>
                                </nav>

                                <div className="ui-btn-outer">
                                    <div className="header-contact">
                                        <div className="social-icon">
                                            <a href="#"><i className="fa-brands fa-facebook-f"></i></a>
                                            <a href="#"><i className="fa-brands fa-x-twitter"></i></a>
                                            <a href="#"><i className="fa-brands fa-instagram"></i></a>
                                        </div>
                                        <a href="tel:+92(8800)9806" className="info-btn">
                                            <i className="icon fa fa-phone"></i>
                                            + 88 ( 9800 ) 6802
                                        </a>
                                    </div>
                                </div>

                                <a href="page-contact.html" className="theme-btn btn-style-one">Free Consultation</a>


                                <div className="mobile-nav-toggler"><span className="icon lnr-icon-bars"></span></div>
                            </div>
                        </div>
                    </div>
                </div>


                <div className="mobile-menu">
                    <div className="menu-backdrop"></div>


                    <nav className="menu-box">
                        <div className="upper-box">
                            <div className="nav-logo">
                                <a href="index.html"><img src="/images/white-logo.png" alt=""/></a>
                            </div>
                            <div className="close-btn"><i className="icon fa fa-times"></i></div>
                        </div>

                        <ul className="navigation clearfix">

                        </ul>
                        <ul className="contact-list-one">
                            <li>

                                <div className="contact-info-box">
                                    <i className="icon lnr-icon-phone-handset"></i>
                                    <span className="title">Call Now</span>
                                    <a href="tel:+92880098670">+92 (8800) - 98670</a>
                                </div>
                            </li>
                            <li>

                                <div className="contact-info-box">
                                    <span className="icon lnr-icon-envelope1"></span>
                                    <span className="title">Send Email</span>
                                    <a href="/cdn-cgi/l/email-protection#0a626f667a4a6965677a6b647324696567"><span
                                        className="__cf_email__" data-cfemail="49212c2539092a262439282730672a2624">[email protected]</span></a>
                                </div>
                            </li>
                            <li>

                                <div className="contact-info-box">
                                    <span className="icon lnr-icon-clock"></span>
                                    <span className="title">Send Email</span>
                                    Mon - Sat 8:00 - 6:30, Sunday - CLOSED
                                </div>
                            </li>
                        </ul>

                        <ul className="social-links">
                            <li>
                                <a href="#"><i className="fab fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="#"><i className="fab fa-facebook-f"></i></a>
                            </li>
                            <li>
                                <a href="#"><i className="fab fa-pinterest"></i></a>
                            </li>
                            <li>
                                <a href="#"><i className="fab fa-instagram"></i></a>
                            </li>
                        </ul>
                    </nav>
                </div>


                <div className="sticky-header">
                    <div className="auto-container">
                        <div className="inner-container">

                            <div className="logo">
                                <a href="index.html"><img src="/images/black-logo.png" alt="img"/></a>
                            </div>


                            <div className="nav-outer">

                                <nav className="main-menu">
                                    <div className="navbar-collapse show collapse clearfix">
                                        <ul className="navigation clearfix">

                                        </ul>
                                    </div>
                                </nav>


                                <div className="mobile-nav-toggler"><span className="icon lnr-icon-bars"></span></div>
                            </div>
                        </div>
                    </div>
                </div>

            </header>

            {children}

            <footer className="footer-section-1 fix footer-bg bg-cover"
                    style={{backgroundImage: "url(images/home-1/footer-shape.png)"}}>
                <span className="circle-shape"></span>
                <span className="circle-shape-2"></span>
                <div className="auto-container">
                    <div className="footer-newsletter-wrapper">
                        <div className="footer-newsletter-left wow fadeInUp" data-wow-delay=".3s">
                            <div className="icon">
                                <i className="lnr-icon-envelope"></i>
                            </div>
                            <h3 className="text-white font-weight-700 font-size-28"> subscribe to <br/> newsletter</h3>
                        </div>
                        <form action="#" className="wow fadeInUp" data-wow-delay=".5s">
                            <div className="form-clt">
                                <input type="text" name="email" id="email2" placeholder="Your email address"/>
                                <button className="arrow-icon" style={{float:"left"}} type="submit">
                                    <i className="lnr-icon-arrow-left"></i>
                                </button>
                            </div>
                        </form>
                    </div>
                    <div className="footer-widget-wrapper">
                        <div className="row justify-content-between">
                            <div className="col-xl-3 col-lg-3 col-md-4 col-sm-6 wow fadeInUp" data-wow-delay=".2s">
                                <div className="footer-widget-items mt-30">
                                    <div className="widget-title mb-25">
                                        <a href="index.html" className="footer-logo">
                                            <img src="/images/white-logo.svg" alt="img"/>
                                        </a>
                                    </div>
                                    <div className="footer-content">
                                        <p>everyone with high and useful reward for his/her trading</p>
                                        <div className="social-icon">
                                            <a href="#"><i className="fa-brands fa-facebook-f"></i></a>
                                            <a href="#"><i className="fa-brands fa-x-twitter"></i></a>
                                            <a href="#"><i className="fa-brands fa-instagram"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-xl-2 col-lg-3 col-md-4 col-sm-6 wow fadeInUp" data-wow-delay=".4s">
                                <div className="footer-widget-items mt-30">
                                    <div className="widget-title mb-25">
                                        <h3 className="font-size-24 text-white font-weight-500">Company</h3>
                                    </div>
                                    <ul className="user-links">
                                        <li><a href="index.html">Home</a></li>
                                        <li><a href="page-about.html">About us</a></li>
                                        <li><a href="page-services.html">Services</a></li>
                                        <li><a href="page-contact.html">Contact Us</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div className="col-xl-2 col-lg-3 col-md-4 col-sm-6 wow fadeInUp" data-wow-delay=".6s">
                                <div className="footer-widget-items mt-30">
                                    <div className="widget-title mb-25">
                                        <h3 className="font-size-24 text-white font-weight-500">Support</h3>
                                    </div>
                                    <ul className="user-links">
                                        <li><a href="page-service-details.html">Customer Support</a></li>
                                        <li><a href="page-service-details.html">Privacy &amp; policy</a></li>
                                        <li><a href="page-service-details.html">Terms &amp; condition</a></li>
                                        <li><a href="page-service-details.html">Help Center</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div className="col-xl-2 col-lg-3 col-md-4 col-sm-6 wow fadeInUp" data-wow-delay=".8s">
                                <div className="footer-widget-items mt-30">
                                    <div className="widget-title mb-25">
                                        <h3 className="font-size-24 text-white font-weight-500">Contact Us</h3>
                                    </div>
                                    <ul className="contact-list">
                                        <li>
                                            <i className="lnr-icon-phone-handset"></i>
                                            <p><a href="tel:+1050055900">+10500-55-900</a></p>
                                        </li>
                                        <li>
                                            <i className="lnr-icon-envelope"></i>
                                            <p><a
                                                href="/cdn-cgi/l/email-protection#76101f18151a1f0e361e131a06580305"><span
                                                className="__cf_email__"
                                                data-cfemail="d395babdb0bfbaab93bbb6bfa3fda6a0">[email protected]</span></a>
                                            </p>
                                        </li>
                                        <li>
                                            <i className="lnr-icon-map-marker"></i>
                                            <p>44 Danwers, NY City, USA, 70-102</p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="footer-bottom">
                    <div className="auto-container">
                        <p className="wow fadeInUp" data-wow-delay=".3s">Copyright © 2025 Finclix. All Rights
                            Reserved</p>
                    </div>
                </div>
            </footer>

        </div>
        <Script src="/js/jquery.js"/>
        <Script src="/js/popper.min.js"/>
        <Script src="/js/bootstrap.min.js"/>
        <Script src="/js/jquery.fancybox.js"/>
        <Script src="/js/jquery-ui.js"/>
        <Script src="/js/gsap.js"/>
        <Script src="/js/gsap-scroll-to-plugin.js"/>
        <Script src="/js/gsap-scroll-smoother.js"/>
        <Script src="/js/gsap-scroll-trigger.js"/>
        <Script src="/js/gsap-split-text.js"/>
        <Script src="/js/split-type.min.js"/>
        <Script src="/js/parallaxie.js"/>
        <Script src="/js/wow.js"/>
        <Script src="/js/bxslider.js"/>
        <Script src="/js/nice-select.min.js"/>
        <Script src="/js/knob.js"/>
        <Script src="/js/appear.js"/>
        <Script src="/js/swiper.min.js"/>
        <Script src="/js/mixitup.js"/>
        <Script src="/js/script.js"/>
        </body>
        </html>
    );
}
